<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.staitech</groupId>
        <artifactId>staitech-modules</artifactId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>staitech-modules-file</artifactId>

    <description>
        staitech-modules-file文件服务
    </description>

    <dependencies>

        <!-- SpringCloud Alibaba Nacos -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- SpringCloud Alibaba Nacos Config -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <!-- SpringCloud Alibaba Sentinel -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>

        <!-- SpringBoot Actuator -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- FastDFS -->
        <dependency>
            <groupId>com.github.tobato</groupId>
            <artifactId>fastdfs-client</artifactId>
        </dependency>

        <!-- Minio -->
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
            <version>${minio.version}</version>
        </dependency>

        <!-- Staitech Api System -->
        <dependency>
            <groupId>cn.staitech</groupId>
            <artifactId>staitech-api-system</artifactId>
        </dependency>

        <!-- Staitech Common Swagger -->
        <dependency>
            <groupId>cn.staitech</groupId>
            <artifactId>staitech-common-swagger</artifactId>
        </dependency>

    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


    <!--配置profiles环境-->
    <profiles>
        <profile>
            <!--开发环境-->
            <id>pacmvsdev</id>
            <properties>
                <activatedProperties>pacmvsdev</activatedProperties>
                <nacosNamespace>pacmvsdev</nacosNamespace>
                <nacosAddress>http://192.168.52.224/:8848</nacosAddress>
                <nacosGroup>DEFAULT_GROUP</nacosGroup>
                <serverAddr>192.168.52.224:8848</serverAddr>
            </properties>
        </profile>

        <profile>
            <!--测试环境-->
            <id>testpvcmvs</id>
            <properties>
                <activatedProperties>testpvcmvs</activatedProperties>
                <nacosNamespace>301f5c59-5f9c-451c-a77b-88d64ddfd9f0</nacosNamespace>
                <nacosAddress>http://192.168.160.105:8848</nacosAddress>
                <nacosGroup>DEFAULT_GROUP</nacosGroup>
                <serverAddr>192.168.160.105:8848</serverAddr>
            </properties>
        </profile>
        <profile>
            <!--生产环境-->
            <id>pathmedics</id>
            <properties>
                <activatedProperties>pathmedics</activatedProperties>
                <nacosNamespace>40438ad6-00f6-4524-8043-4e79819cccf0</nacosNamespace>
                <nacosAddress>http://10.10.4.13:8848</nacosAddress>
                <nacosGroup>DEFAULT_GROUP</nacosGroup>
                <serverAddr>10.10.4.13:8848</serverAddr>
            </properties>
        </profile>
    </profiles>

</project>