# 基础镜像
FROM nginx
# author
MAINTAINER staitech

# 挂载目录
VOLUME /home/staitech/projects/staitech-ui
# 创建目录
RUN mkdir -p /home/staitech/projects/staitech-ui
# 指定路径
WORKDIR /home/staitech/projects/staitech-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/staitech/projects/staitech-ui
