<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.staitech</groupId>
        <artifactId>staitech</artifactId>
        <version>1.0.0</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>staitech-system</module>
        <module>staitech-job</module>
        <module>staitech-file</module>
    </modules>

    <artifactId>staitech-modules</artifactId>
    <packaging>pom</packaging>

    <description>
        staitech-modules业务模块
    </description>
</project>
