# 基础镜像
#FROM openjdk:17-oracle
FROM  openjdk:8-jre
# author
MAINTAINER staitech

# 挂载目录
VOLUME /home/staitech
# 创建目录
RUN mkdir -p /home/staitech
# 指定路径
WORKDIR /home/staitech
# 复制jar文件到路径
COPY ./jar/staitech-gateway.jar /home/staitech/staitech-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-Dreactor.netty.pool.leasingStrategy=lifo","-jar","staitech-gateway.jar"]